In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2307, 8231, 5498, 3190],
 [2307, 8231, 5498, 201],
 [2307, 1555, 5498, 3673],
 [8513, 5201, 9324, 3630, 875],
 [8513, 5201, 9324, 3630, 7361],
 [8526, 2307, 2712, 5498, 3905],
 [8964, 432, 1269, 3630]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2307 8231 5498 3190]
 [   0    0    0    0 2307 8231 5498  201]
 [   0    0    0    0 2307 1555 5498 3673]
 [   0    0    0 8513 5201 9324 3630  875]
 [   0    0    0 8513 5201 9324 3630 7361]
 [   0    0    0 8526 2307 2712 5498 3905]
 [   0    0    0    0 8964  432 1269 3630]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 285ms/step


array([[[ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,
          0.03789416,  0.03113419,  0.00553808,  0.021675  ,
         -0.00413794,  0.04739714],
        [ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,
          0.03789416,  0.03113419,  0.00553808,  0.021675  ,
         -0.00413794,  0.04739714],
        [ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,
          0.03789416,  0.03113419,  0.00553808,  0.021675  ,
         -0.00413794,  0.04739714],
        [ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,
          0.03789416,  0.03113419,  0.00553808,  0.021675  ,
         -0.00413794,  0.04739714],
        [-0.00877995, -0.04614083, -0.01314158, -0.0139192 ,
         -0.00136235, -0.03845208, -0.01237264, -0.04314697,
          0.01415225,  0.01564702],
        [ 0.00835108,  0.01445809,  0.01593517,  0.01342488,
          0.0221892 , -0.04234349,  0.0311699 ,  0.0263758 ,
          0.03601464,  0.0390489 ],
        [ 0.0054969 ,  0.04557068, -0.02508838,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 2307, 8231, 5498, 3190])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 60ms/step


array([[ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,  0.03789416,
         0.03113419,  0.00553808,  0.021675  , -0.00413794,  0.04739714],
       [ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,  0.03789416,
         0.03113419,  0.00553808,  0.021675  , -0.00413794,  0.04739714],
       [ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,  0.03789416,
         0.03113419,  0.00553808,  0.021675  , -0.00413794,  0.04739714],
       [ 0.0340173 ,  0.02499798, -0.0367546 , -0.03405734,  0.03789416,
         0.03113419,  0.00553808,  0.021675  , -0.00413794,  0.04739714],
       [-0.00877995, -0.04614083, -0.01314158, -0.0139192 , -0.00136235,
        -0.03845208, -0.01237264, -0.04314697,  0.01415225,  0.01564702],
       [ 0.00835108,  0.01445809,  0.01593517,  0.01342488,  0.0221892 ,
        -0.04234349,  0.0311699 ,  0.0263758 ,  0.03601464,  0.0390489 ],
       [ 0.0054969 ,  0.04557068, -0.02508838,  0.01570696,  0.04661315,
         0.04858358, -0.03513063, -0.04571481